INSERT INTO UTILISATEUR VALUES(1, 'Administrateur', 'dnypru', 'Administrateur', '', '', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
PRINT '*** TYPE_DOCUMENT ***'
INSERT INTO TYPE_DOCUMENT VALUES ('a', 'Livre', 'ﬂ «»', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('b', 'PÈriodique', 'œÊ—Ì…', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('c', 'ThËse', '√ÿ—ÊÕ…', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('d', 'Article', '„ﬁ«·', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('e', 'Document audio-visuel', 'ÊÀÌﬁ… ”„⁄Ì… »’—Ì…', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('f', 'Document cartographique', 'Œ—Ìÿ… Ê „Œÿÿ', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('g', 'Ressource Èlectronique', '„’œ— «·ﬂ —Ê‰Ì', 'C:\')
INSERT INTO TYPE_DOCUMENT VALUES ('x', 'Autre', '¬Œ—', 'C:\')
PRINT '*** SUPPORT ***'
INSERT INTO SUPPORT VALUES (1, 'Livre', 'ﬂ «»')
INSERT INTO SUPPORT VALUES (2, 'PÈriodique', 'œÊ—Ì…')
INSERT INTO SUPPORT VALUES (3, 'CDROM/DVD', 'ﬁ—’ „÷€Êÿ')
INSERT INTO SUPPORT VALUES (4, 'CD Audio', 'ﬁ—’ ”„⁄Ì')
INSERT INTO SUPPORT VALUES (5, 'Cassette vidÈo', '‘—Ìÿ ›ÌœÌÊ')
INSERT INTO SUPPORT VALUES (6, 'Carte/plan', 'Œ—Ìÿ…/„Œÿÿ')
PRINT '*** INDICATION_GENERALE ***'
INSERT INTO INDICATION VALUES ('a', 'texte imprimÈ', '‰’ „ÿ»Ê⁄')
INSERT INTO INDICATION VALUES ('b', 'texte manuscrit', '‰’ „ŒÿÊÿ')
INSERT INTO INDICATION VALUES ('c', 'partition musicale imprimÈe', 'ﬁÿ⁄… „Ê”ﬁÌ… „ÿ»Ê⁄…')
INSERT INTO INDICATION VALUES ('d', 'partition musicale manuscrite', 'ﬁÿ⁄… „Ê”ﬁÌ… „ŒÿÊÿ…')
INSERT INTO INDICATION VALUES ('e', 'document cartographique imprimÈ', 'Œ—Ìÿ… „ÿ»Ê⁄…')
INSERT INTO INDICATION VALUES ('f', 'document cartographique manuscrit', 'Œ—Ìÿ… „ŒÿÊÿ…')
INSERT INTO INDICATION VALUES ('g', 'document projetÈ ou vidÈo', '›ÌœÌÊ')
INSERT INTO INDICATION VALUES ('i', 'enregistrement sonore non musical', ' ”ÃÌ· ’Ê Ì €Ì— „Ê”ÌﬁÌ')
INSERT INTO INDICATION VALUES ('j', 'enregistrement sonore musical', ' ”ÃÌ· ’Ê Ì „Ê”ÌﬁÌ')
INSERT INTO INDICATION VALUES ('k', 'document graphique ‡ deux dimensions', 'ÊÀÌﬁ… ŒÿÌ… À‰«∆Ì… «·»⁄œ')
INSERT INTO INDICATION VALUES ('l', 'document Èlectronique', 'ÊÀÌﬁ… «·ﬂ —Ê‰Ì…')
INSERT INTO INDICATION VALUES ('m', 'document multimÈdia', 'ÊÀÌﬁ… „ ⁄œœ… «·Ê”«∆ÿ')
INSERT INTO INDICATION VALUES ('r', 'objet ‡ 3 dimensions, artefacts, ...', '„Ã”„ À·«ÀÌ «·√»⁄«œ')
PRINT '*** TYPE_VEDETTE ***'
INSERT INTO TYPE_VEDETTE VALUES (1, 'Nom de personne', '≈”„ ‘Œ’', '600', '700')
INSERT INTO TYPE_VEDETTE VALUES (2, 'CollectivitÈ', '≈”„ «·ÂÌ∆…', '601', '710')
INSERT INTO TYPE_VEDETTE VALUES (3, 'Nom de famille', '≈”„ ⁄«∆·Ì', '602', '720')
INSERT INTO TYPE_VEDETTE VALUES (4, 'Auteur/titre', '⁄‰Ê«‰/„ƒ·›', '604', '730')
INSERT INTO TYPE_VEDETTE VALUES (5, 'Titre uniforme', '⁄‰Ê«‰ „ÊÕœ', '605', '0')
INSERT INTO TYPE_VEDETTE VALUES (6, 'Nom commun', '«·ﬂ·„«  «·„› «ÕÌ…', '606', '0')
INSERT INTO TYPE_VEDETTE VALUES (7, 'Nom gÈographique', '«”„ «·Ã€—«›Ï', '607', '0')
INSERT INTO TYPE_VEDETTE VALUES (8, 'Forme, genre ou caractÈristique physique', '‘ﬂ·,‰Ê⁄ √Ê Œ«’Ì… „«œÌ…', '608', '0')
INSERT INTO TYPE_VEDETTE VALUES (9, 'Indexation libre', ' ﬂ‘Ì› «·Õ—', '610', '0')
INSERT INTO TYPE_VEDETTE VALUES (10, 'Marque dÈposÈe', '⁄·«„… „”Ã·…', '616', '716')
PRINT '*** RELATION ***'
INSERT INTO RELATION VALUES (461, 'contenu dans', 'Contient', '„Õ ÊÌ ›Ì', 'ÌÕ ÊÌ')
INSERT INTO RELATION VALUES (462, 'fait partie de', 'Est composÈ de', '„ ÷„‰ ›Ì', '„ ﬂÊ‰ „‰')
INSERT INTO RELATION VALUES (463, 'in', 'Contenu', '›Ì', '„Õ ÊÌ')
INSERT INTO RELATION VALUES (464, 'est un bulletin de', 'Bulletins', '‰‘—… ·', '‰‘—« ')
PRINT '*** STATUT_NOTICE ***'
INSERT INTO STATUT_NOTICE VALUES (1, 'En traitement', 'ﬁÌœ «·„⁄«·Ã…')
INSERT INTO STATUT_NOTICE VALUES (2, 'Provisoire', '„ƒﬁ ')
INSERT INTO STATUT_NOTICE VALUES (3, 'En commande', '›Ì «·ÿ·»')
INSERT INTO STATUT_NOTICE VALUES (4, 'ValidÈe', 'ﬂ«„·…')
PRINT '*** STATUT_EXEMPLAIRE ***'
INSERT INTO STATUT_EXEMPLAIRE VALUES (1, 'En dÈpÙt', '›Ì «Ìœ«⁄')
INSERT INTO STATUT_EXEMPLAIRE VALUES (2, 'PrÍt externe', '«⁄«—… Œ«—ÃÌ…')
INSERT INTO STATUT_EXEMPLAIRE VALUES (3, 'Consultation sur place', '«⁄«—… œ«Œ·Ì…')
INSERT INTO STATUT_EXEMPLAIRE VALUES (4, 'Disponible pour le PEB', '„ Ê›— ··≈⁄«—… „« »Ì‰ «·„ﬂ »« ')
INSERT INTO STATUT_EXEMPLAIRE VALUES (5, 'DÈtÈriorÈ', '„ ·›')
INSERT INTO STATUT_EXEMPLAIRE VALUES (6, 'Perdu', '„›ﬁÊœ')
INSERT INTO STATUT_EXEMPLAIRE VALUES (7, 'EchangÈ', '„” »œ·')
INSERT INTO STATUT_EXEMPLAIRE VALUES (8, 'CÈdÈ', '„Âœ«…')
PRINT '*** MODE_ACQUISITION ***'
INSERT INTO MODE_ACQUISITION VALUES (1, 'Achat', '‘—«¡')
INSERT INTO MODE_ACQUISITION VALUES (2, 'Don', '≈Âœ«¡')
INSERT INTO MODE_ACQUISITION VALUES (3, 'Echange', ' »«œ·')
INSERT INTO MODE_ACQUISITION VALUES (4, 'DÈpÙt', '≈Ìœ«⁄')
INSERT INTO MODE_ACQUISITION VALUES (5, 'Passif', 'ﬁ«œ„')
PRINT '*** MONNAIE ***'
INSERT INTO MONNAIE VALUES (1, 'Dinar', 'œÌ‰«—', 'DZD', 'œÃ')
INSERT INTO MONNAIE VALUES (2, 'Dollar (USA)', 'œÊ·«—', 'USD', '$')
INSERT INTO MONNAIE VALUES (3, 'Euro', '√Ê—Ê', 'EUR', '√Ê—Ê')
PRINT '*** PERIODICITE ***'
INSERT INTO PERIODICITE VALUES ('a', 'quotidienne', 'ÌÊ„Ì…')
INSERT INTO PERIODICITE VALUES ('b', 'bihebdomadaire (deux fois par semaine)', '‰’› √”»Ê⁄Ì…')
INSERT INTO PERIODICITE VALUES ('c', 'hebdomadaire', '√”»Ê⁄Ì…')
INSERT INTO PERIODICITE VALUES ('d', 'toutes les deux semaines', ' ’œ— ﬂ· √”»Ê⁄Ì‰')
INSERT INTO PERIODICITE VALUES ('e', 'bimensuelle (deux fois par mois)', ' ’œ— ﬂ· ‘Â—Ì‰')
INSERT INTO PERIODICITE VALUES ('f', 'mensuelle', '‘Â—Ì…')
INSERT INTO PERIODICITE VALUES ('g', 'bimestrielle (tous les deux mois)', ' ’œ— ﬂ· ‘Â—Ì‰')
INSERT INTO PERIODICITE VALUES ('h', 'trimestrielle', ' ’œ— ﬂ· À·«À… √‘Â—')
INSERT INTO PERIODICITE VALUES ('i', 'trois fois par an', ' ’œ— À·«À… „—«  ›Ï «·”‰…')
INSERT INTO PERIODICITE VALUES ('j', 'semestrielle (deux fois par an)', ' ’œ— ﬂ· À·«À… √‘Â—')
INSERT INTO PERIODICITE VALUES ('k', 'annuelle', '”‰ÊÌ…')
INSERT INTO PERIODICITE VALUES ('l', 'bisannuelle (tous les deux ans)', ' ’œ— ﬂ· ”‰ Ì‰')
INSERT INTO PERIODICITE VALUES ('m', 'triennale (tous les trois ans)', ' ’œ— ﬂ· À·«À… ”‰Ê« ')
INSERT INTO PERIODICITE VALUES ('n', 'trois fois par semaine', ' ’œ— À·«À „—«  ›Ì «·√”»Ê⁄')
INSERT INTO PERIODICITE VALUES ('o', 'trois fois par mois', ' ’œ— À·«À… „—«  ›Ï «·√”»Ê⁄')
INSERT INTO PERIODICITE VALUES ('p', 'mise ‡ jour permanente', ' ÕœÌÀ „” „—')
INSERT INTO PERIODICITE VALUES ('u', 'pÈriodicitÈ inconnue', ' Ê« —«  €Ì— „⁄—Ê›…')
INSERT INTO PERIODICITE VALUES ('y', 'sans pÈriodicitÈ', '€Ì— „‰ Ÿ„…')
INSERT INTO PERIODICITE VALUES ('z', 'autre', ' Ê« —«  √Œ—Ï')
PRINT '*** LANGUE ***'
INSERT INTO LANGUE VALUES ('afr', 'Afrikaan', '√›—Ìﬂ«‰Ì…')
INSERT INTO LANGUE VALUES ('alb', 'Albanais', '√·»«‰Ì…')
INSERT INTO LANGUE VALUES ('ame', 'AmÈricain', '√„—ÌﬂÌ…')
INSERT INTO LANGUE VALUES ('amh', 'Amharique', '√„Â—Ì…')
INSERT INTO LANGUE VALUES ('ang', 'Anglo-saxon', '√‰Ã·Ê”ﬂ”Ê‰Ì…')
INSERT INTO LANGUE VALUES ('ara', 'Arabe', '⁄—»Ì…')
INSERT INTO LANGUE VALUES ('arm', 'ArmÈnien', '√—„‰Ì…')
INSERT INTO LANGUE VALUES ('aus', 'Australien', '«·√” —«·Ì…')
INSERT INTO LANGUE VALUES ('aze', 'AzÈri', '√–—Ì…')
INSERT INTO LANGUE VALUES ('bak', 'Bachkir', '»‘ﬂÌ—Ì…')
INSERT INTO LANGUE VALUES ('bal', 'Baloutchi', '»·Ê‘Ì…')
INSERT INTO LANGUE VALUES ('baq', 'Basque', '»«”ﬂÌ…')
INSERT INTO LANGUE VALUES ('ben', 'Bengali', '»‰€«·Ì…')
INSERT INTO LANGUE VALUES ('ber', 'BerbËre', '»—»—Ì…')
INSERT INTO LANGUE VALUES ('brz', 'Bresilien', '»—«“Ì·Ì…')
INSERT INTO LANGUE VALUES ('bul', 'Bulgare', '»·€«—Ì…')
INSERT INTO LANGUE VALUES ('cat', 'Catalan', 'ﬁÿ·Ê‰Ì…')
INSERT INTO LANGUE VALUES ('che', 'TchÈtchËne', '‘Ì‘«‰Ì…')
INSERT INTO LANGUE VALUES ('chi', 'Chinois', '’Ì‰Ì…')
INSERT INTO LANGUE VALUES ('cze', 'TchËque', ' ‘ÌﬂÌ…')
INSERT INTO LANGUE VALUES ('dan', 'Danois', 'œ«‰„«—ﬂÌ…')
INSERT INTO LANGUE VALUES ('dut', 'NÈerlandais', 'ÂÊ·‰œÌ…')
INSERT INTO LANGUE VALUES ('eng', 'Anglais', '≈‰Ã·Ì“Ì…')
INSERT INTO LANGUE VALUES ('est', 'Estonien', '≈” Ê‰Ì…')
INSERT INTO LANGUE VALUES ('fin', 'Finnois', '›‰·‰œÌ…')
INSERT INTO LANGUE VALUES ('fre', 'FranÁais', '›—‰”Ì…')
INSERT INTO LANGUE VALUES ('gag', 'Galicien', 'Ã·ÌﬁÌ…')
INSERT INTO LANGUE VALUES ('geo', 'GÈorgien', 'ÃÊ—ÃÌ…')
INSERT INTO LANGUE VALUES ('ger', 'Allemand', '√·„«‰Ì…')
INSERT INTO LANGUE VALUES ('gre', 'Grec moderne', 'ÌÊ‰«‰Ì…')
INSERT INTO LANGUE VALUES ('hau', 'Haoussa', '«·Â«Ê”«')
INSERT INTO LANGUE VALUES ('heb', 'HÈbreu', '⁄»—Ì…')
INSERT INTO LANGUE VALUES ('hun', 'Hongrois', '„Ã—Ì…')
INSERT INTO LANGUE VALUES ('ice', 'Islandais', '¬Ì”·‰œÌ…')
INSERT INTO LANGUE VALUES ('ind', 'IndonÈsien', '≈‰œÊ‰Ì”Ì…')
INSERT INTO LANGUE VALUES ('iri', 'Irlandais', '«Ì—·‰œÌ…')
INSERT INTO LANGUE VALUES ('ita', 'Italien', '≈Ìÿ«·Ì…')
INSERT INTO LANGUE VALUES ('jav', 'Javanais', 'Ã«ÊÌ…')
INSERT INTO LANGUE VALUES ('jpn', 'Japonais', 'Ì«»«‰Ì…')
INSERT INTO LANGUE VALUES ('kur', 'Kurde', 'ﬂ—œÌ…')
INSERT INTO LANGUE VALUES ('lat', 'Latin', '·« Ì‰Ì…')
INSERT INTO LANGUE VALUES ('lav', 'Letton', '·« ›Ì…')
INSERT INTO LANGUE VALUES ('lit', 'Lithuanien', '· Ê«‰Ì…')
INSERT INTO LANGUE VALUES ('mac', 'MacÈdonien', '„ﬁœÊ‰Ì…')
INSERT INTO LANGUE VALUES ('mao', 'Maori', '„«Ê—Ì…')
INSERT INTO LANGUE VALUES ('mlt', 'Maltais', '„«·ÿÌ…')
INSERT INTO LANGUE VALUES ('pan', 'Pendjabi', '»‰Ã«»Ì…')
INSERT INTO LANGUE VALUES ('per', 'Persan moderne', '›«—”Ì…')
INSERT INTO LANGUE VALUES ('pol', 'Polonais', '»Ê·‰œÌ…')
INSERT INTO LANGUE VALUES ('por', 'Portugais', '»— €«·Ì…')
INSERT INTO LANGUE VALUES ('rum', 'Roumain', '—Ê„«‰Ì…')
INSERT INTO LANGUE VALUES ('rus', 'Russe', '—Ê”Ì…')
INSERT INTO LANGUE VALUES ('slo', 'Slovaque', '”·Ê›«ﬂÌ…')
INSERT INTO LANGUE VALUES ('slv', 'SlovËne', '”·Ê›Ì‰Ì…')
INSERT INTO LANGUE VALUES ('snh', 'Singhalais', '”‰Â«·Ì…')
INSERT INTO LANGUE VALUES ('som', 'Somali', '’Ê„«·Ì…')
INSERT INTO LANGUE VALUES ('swa', 'Swahili', '”Ê«Õ·Ì…')
INSERT INTO LANGUE VALUES ('swe', 'SuÈdois', '”ÊÌœÌ…')
INSERT INTO LANGUE VALUES ('syr', 'Syriaque', '”—Ì«‰Ì…')
INSERT INTO LANGUE VALUES ('tam', 'Tamoul', ' «„Ì·Ì…')
INSERT INTO LANGUE VALUES ('tha', 'ThaÔ', ' «Ì·‰œÌ…')
INSERT INTO LANGUE VALUES ('tus', 'Turc', ' —ﬂÌ…')
INSERT INTO LANGUE VALUES ('ukr', 'Ukrainien', '√Êﬂ—«‰Ì…')
INSERT INTO LANGUE VALUES ('und', 'Inconnue', '€Ì— „⁄—Ê›…')
INSERT INTO LANGUE VALUES ('urd', 'Urdu', '√—œÌ…')
INSERT INTO LANGUE VALUES ('uzb', 'Uzbek', '√Ê“»ﬂÌ…')
INSERT INTO LANGUE VALUES ('vie', 'Vietnamien', '›Ì ‰«„Ì…')
INSERT INTO LANGUE VALUES ('wel', 'Gallois', 'ÊÌ·“Ì…')
INSERT INTO LANGUE VALUES ('wol', 'Wolof', 'Ê·Ê›Ì…')
INSERT INTO LANGUE VALUES ('yid', 'Yiddish', 'ÌœÌ‘Ì…')
INSERT INTO LANGUE VALUES ('yor', 'Yoruba', 'ÌÊ—Ê»«')
INSERT INTO LANGUE VALUES ('zul', 'Zoulou', '“Ê·Ê')
PRINT '*** PAYS ***'
INSERT INTO PAYS VALUES ('AF', 'Afghanistan', '√›€«‰” «‰')
INSERT INTO PAYS VALUES ('ZA', 'Afrique du Sud', '≈›—ÌﬁÌ« «·Ã‰Ê»Ì…')
INSERT INTO PAYS VALUES ('AL', 'Albanie', '√·»«‰Ì«')
INSERT INTO PAYS VALUES ('DZ', 'AlgÈrie', '«·Ã“«∆—')
INSERT INTO PAYS VALUES ('DE', 'Allemagne', '√·„«‰Ì«')
INSERT INTO PAYS VALUES ('DD', 'Allemagne de l''Est', '√·„«‰Ì« «·‘—ﬁÌ…')
INSERT INTO PAYS VALUES ('AD', 'Andorre', '√‰œÊ—«')
INSERT INTO PAYS VALUES ('AO', 'Angola', '√‰€Ê·«')
INSERT INTO PAYS VALUES ('AQ', 'Antartique', '√‰ —ﬂ Ìﬂ«')
INSERT INTO PAYS VALUES ('AG', 'Antigua et Barbuda', '√‰ Ì€« Ê»«—»Êœ«')
INSERT INTO PAYS VALUES ('AN', 'Antilles nÈerlandaises', 'Ã“— «·√‰ Ì· «·ÂÊ·‰œÌ…')
INSERT INTO PAYS VALUES ('SA', 'Arabie saoudite', '««·”⁄ÊœÌ…')
INSERT INTO PAYS VALUES ('AR', 'Argentine', '«·√—Ã‰ Ì‰')
INSERT INTO PAYS VALUES ('AM', 'ArmÈnie', '√—„Ì‰Ì«')
INSERT INTO PAYS VALUES ('AW', 'Aruba', '√—Ê»«')
INSERT INTO PAYS VALUES ('AU', 'Australie', '√” —«·Ì«')
INSERT INTO PAYS VALUES ('AT', 'Autriche', '‰„”«')
INSERT INTO PAYS VALUES ('AZ', 'AzrbaÔdjan', '√–—»ÌÃ«‰')
INSERT INTO PAYS VALUES ('BS', 'Bahamas', '«·»Â«„«')
INSERT INTO PAYS VALUES ('BH', 'BahreÔen', '«·»Õ—Ì‰')
INSERT INTO PAYS VALUES ('BD', 'Bangladesh', '»‰€·«œÌ‘')
INSERT INTO PAYS VALUES ('BB', 'Barbade', '»«—»«œÊ”')
INSERT INTO PAYS VALUES ('BE', 'Belgique', '»·ÃÌﬂ«')
INSERT INTO PAYS VALUES ('BZ', 'Belize', '»·Ì“')
INSERT INTO PAYS VALUES ('BM', 'Bermudes', 'Ã“— »—„Êœ«')
INSERT INTO PAYS VALUES ('BT', 'Bhoutan', '»Ê «‰')
INSERT INTO PAYS VALUES ('BY', 'BiÈlorussie (BÈlarus)', '—Ê”Ì« «·»Ì÷«¡')
INSERT INTO PAYS VALUES ('BO', 'Bolivie', '»Ê·Ì›Ì«')
INSERT INTO PAYS VALUES ('BA', 'Bosnie-HerzÈgovine', '«·»Ê”‰… Ê«·Â—”ﬂ')
INSERT INTO PAYS VALUES ('BW', 'Botswana', '»Ê ”Ê«‰«')
INSERT INTO PAYS VALUES ('BN', 'Brunei', '»—Ê‰«Ì')
INSERT INTO PAYS VALUES ('BR', 'BrÈsil', '«·»—«“Ì·')
INSERT INTO PAYS VALUES ('BG', 'Bulgarie', '»·€«—Ì«')
INSERT INTO PAYS VALUES ('BF', 'Burkina Faso', '»Ê—ﬂÌ‰« ›«”Ê')
INSERT INTO PAYS VALUES ('BI', 'Burundi', '»Ê—Ê‰œÌ')
INSERT INTO PAYS VALUES ('BJ', 'BÈnin', '»‰Ì‰')
INSERT INTO PAYS VALUES ('KH', 'Cambodge', 'ﬂ„»ÊœÌ«')
INSERT INTO PAYS VALUES ('CM', 'Cameroun', '«·ﬂ«„Ì—Ê‰')
INSERT INTO PAYS VALUES ('CA', 'Canada', 'ﬂ‰œ«')
INSERT INTO PAYS VALUES ('CV', 'Cap vert (Óles)', '«·—√” «·√Œ÷—')
INSERT INTO PAYS VALUES ('KY', 'CaÔmans (Óles)', 'Ã“— ﬂ«Ì„«‰')
INSERT INTO PAYS VALUES ('CF', 'Centrafricaine (RÈpublique)', '≈›—ÌﬁÌ« «·Ê”ÿÏ')
INSERT INTO PAYS VALUES ('CL', 'Chili', ' ‘Ì·Ì')
INSERT INTO PAYS VALUES ('CN', 'Chine', 'Ã„ÂÊ—Ì… «·’Ì‰ «·‘⁄»Ì…')
INSERT INTO PAYS VALUES ('CX', 'Christmas (Óle)', 'Ã“Ì—… ⁄Ìœ «·„Ì·«œ')
INSERT INTO PAYS VALUES ('CY', 'Chypre', 'ﬁ»—’')
INSERT INTO PAYS VALUES ('CC', 'Cocos (Keeling) (Óles)', 'Ã“— ﬂÊﬂ”')
INSERT INTO PAYS VALUES ('CO', 'Colombie', 'ﬂÊ·Ê„»Ì«')
INSERT INTO PAYS VALUES ('KM', 'Comores', 'Ã“— «·ﬁ„—')
INSERT INTO PAYS VALUES ('CG', 'Congo', 'Ã„ÂÊ—Ì… «·ﬂÊ‰€Ê')
INSERT INTO PAYS VALUES ('CK', 'Cook (Óles)', 'Ã“— ﬂÊﬂ')
INSERT INTO PAYS VALUES ('KP', 'CorÈe du Nord', 'ﬂÊ—Ì« «·‘„«·Ì…')
INSERT INTO PAYS VALUES ('KR', 'CorÈe du Sud', 'ﬂÊ—Ì« «·Ã‰Ê»Ì…')
INSERT INTO PAYS VALUES ('CR', 'Costa Rica', 'ﬂÊ” «—Ìﬂ«')
INSERT INTO PAYS VALUES ('HR', 'Croatie', 'ﬂ—Ê« Ì«')
INSERT INTO PAYS VALUES ('CU', 'Cuba', 'ﬂÊ»«')
INSERT INTO PAYS VALUES ('CI', 'CÙte d''ivoire', '”«Õ· «·⁄«Ã')
INSERT INTO PAYS VALUES ('DK', 'Danemark', '«·œ«‰„«—ﬂ')
INSERT INTO PAYS VALUES ('GJ', 'Djibouti', 'ÃÌ»Ê Ì')
INSERT INTO PAYS VALUES ('DO', 'Dominicaine (RÈpublique)', 'Ã„ÂÊ—Ì… «·œÊ„‰Ìﬂ«‰')
INSERT INTO PAYS VALUES ('DM', 'Dominique (RÈpublique)', 'œÊ„Ì‰Ìﬂ«')
INSERT INTO PAYS VALUES ('EG', 'Egypte', '„’—')
INSERT INTO PAYS VALUES ('SV', 'El Salvador', '«·”·›«œÊ—')
INSERT INTO PAYS VALUES ('AE', 'Emirats Arabes Unis', '«·≈„«—« ')
INSERT INTO PAYS VALUES ('EC', 'Equateur', '«·≈ﬂÊ«œÊ—')
INSERT INTO PAYS VALUES ('ER', 'ErythrÈe', '≈—Ì —Ì«')
INSERT INTO PAYS VALUES ('ES', 'Espagne', '≈”»«‰Ì«')
INSERT INTO PAYS VALUES ('EE', 'Estonie', '≈” Ê‰Ì«')
INSERT INTO PAYS VALUES ('US', 'Etats-Unis', '«·Ê·«Ì«  «·„ Õœ…')
INSERT INTO PAYS VALUES ('ET', 'Ethiopie', '≈ÀÌÊ»Ì«')
INSERT INTO PAYS VALUES ('FK', 'Falkland (Óles)', 'Falkland (Óles)')
INSERT INTO PAYS VALUES ('FJ', 'Fidji (Óles)', '›ÌÃÌ')
INSERT INTO PAYS VALUES ('FI', 'Finlande', '›‰·‰œ«')
INSERT INTO PAYS VALUES ('FR', 'France', '›—‰”«')
INSERT INTO PAYS VALUES ('FO', 'FÈroÈ (Óles)', 'Ã“— ›«—Ê')
INSERT INTO PAYS VALUES ('GA', 'Gabon', '«·€«»Ê‰')
INSERT INTO PAYS VALUES ('GM', 'Gambie', '€«„»Ì«')
INSERT INTO PAYS VALUES ('GH', 'Ghana', '€«‰«')
INSERT INTO PAYS VALUES ('GI', 'Gibraltar', 'Ã»« ÿ«—ﬁ')
INSERT INTO PAYS VALUES ('GB', 'Grande-Bretagne (Royaume Uni)', '«·„„·ﬂ… «·„ Õœ…')
INSERT INTO PAYS VALUES ('GD', 'Grenade', '€—Ì‰«œ«')
INSERT INTO PAYS VALUES ('GL', 'Groenland', 'Ã—Ì‰·«‰œ')
INSERT INTO PAYS VALUES ('GR', 'GrËce', '«·ÌÊ‰«‰')
INSERT INTO PAYS VALUES ('GU', 'Guam', '€Ê«„')
INSERT INTO PAYS VALUES ('GT', 'Guatemala', '€Ê« Ì„«·«')
INSERT INTO PAYS VALUES ('GN', 'GuinÈe', '€Ì‰Ì«')
INSERT INTO PAYS VALUES ('GW', 'GuinÈe-Bissau', '€Ì‰Ì« »Ì”«Ê')
INSERT INTO PAYS VALUES ('GQ', 'GuinÈe-Èquatoriale', '€Ì‰Ì« «·«” Ê«∆Ì…')
INSERT INTO PAYS VALUES ('GY', 'Guyana', '€ÊÌ«‰«')
INSERT INTO PAYS VALUES ('GF', 'Guyanne franÁaise', '€ÊÌ«‰« «·›—‰”Ì…')
INSERT INTO PAYS VALUES ('GE', 'GÈorgie', 'ÃÊ—ÃÌ«')
INSERT INTO PAYS VALUES ('GS', 'GÈorgie du Sud', 'Ã—ÃÌ« «·Ã‰Ê»Ì…')
INSERT INTO PAYS VALUES ('HT', 'HaÔti', 'Â«Ì Ì')
INSERT INTO PAYS VALUES ('HN', 'Honduras', 'Â‰œÊ—«”')
INSERT INTO PAYS VALUES ('HK', 'Hong Kong', 'ÂÊ‰€ ﬂÊ‰€')
INSERT INTO PAYS VALUES ('HU', 'Hongrie', '«·„Ã—')
INSERT INTO PAYS VALUES ('IN', 'Inde', '«·Â‰œ')
INSERT INTO PAYS VALUES ('ID', 'IndonÈsie', '≈‰œÊ‰”Ì«')
INSERT INTO PAYS VALUES ('IR', 'Iran', '≈Ì—«‰')
INSERT INTO PAYS VALUES ('IQ', 'Iraq', '«·⁄—«ﬁ')
INSERT INTO PAYS VALUES ('IE', 'Irlande', 'Ã„ÂÊ—Ì… √Ì—·‰œ«')
INSERT INTO PAYS VALUES ('IS', 'Islande', '√Ì”·‰œ«')
INSERT INTO PAYS VALUES ('IL', 'IsraÎl', '≈”—«∆Ì·')
INSERT INTO PAYS VALUES ('IT', 'Italie', '≈ÿ«·Ì«')
INSERT INTO PAYS VALUES ('JM', 'JamaÔque', 'Ã«„Ìﬂ«')
INSERT INTO PAYS VALUES ('JP', 'Japon', '«·Ì«»«‰')
INSERT INTO PAYS VALUES ('JO', 'Jordanie', '«·√—œ‰')
INSERT INTO PAYS VALUES ('KZ', 'Kazakhstan', 'ﬂ«“«Œ” «‰')
INSERT INTO PAYS VALUES ('KE', 'Kenya', 'ﬂÌ‰Ì«')
INSERT INTO PAYS VALUES ('KG', 'Kirghizistan', 'ﬁ—€Ì“” «‰')
INSERT INTO PAYS VALUES ('KI', 'Kiribati', 'ﬂÌ—Ì»«”')
INSERT INTO PAYS VALUES ('KW', 'KoweÔt', '«·ﬂÊÌ ')
INSERT INTO PAYS VALUES ('LA', 'Laos', '·«Ê”')
INSERT INTO PAYS VALUES ('LS', 'Lesotho', '·Ì”Ê Ê')
INSERT INTO PAYS VALUES ('LV', 'Lettonie', '·« ›Ì«')
INSERT INTO PAYS VALUES ('LB', 'Liban', '·»‰«‰')
INSERT INTO PAYS VALUES ('LR', 'Liberia', '·Ì»Ì—Ì«')
INSERT INTO PAYS VALUES ('LY', 'Libye', '·Ì»Ì«')
INSERT INTO PAYS VALUES ('LI', 'Liechtenstein', '·ÌŒ ‰‘ «Ì‰')
INSERT INTO PAYS VALUES ('LT', 'Lituanie', '·Ì Ê«‰Ì«')
INSERT INTO PAYS VALUES ('LU', 'Luxembourg', '·Êﬂ”„»Ê—€')
INSERT INTO PAYS VALUES ('MO', 'Macao', '„«ﬂ«Ê')
INSERT INTO PAYS VALUES ('MK', 'MacÈdoine', '„ﬁœÊ‰Ì«')
INSERT INTO PAYS VALUES ('MG', 'Madagascar', '„œ€‘ﬁ—')
INSERT INTO PAYS VALUES ('MY', 'Malaisie', '„«·Ì“Ì«')
INSERT INTO PAYS VALUES ('MW', 'Malawi', '„·«ÊÌ')
INSERT INTO PAYS VALUES ('MV', 'Maldives', '«·„«·œÌ›')
INSERT INTO PAYS VALUES ('ML', 'Mali', '„«·Ì')
INSERT INTO PAYS VALUES ('MT', 'Malte', '„«·ÿ«')
INSERT INTO PAYS VALUES ('PA', 'Panama', '»‰„«')
INSERT INTO PAYS VALUES ('MP', 'Mariannes du Nord (Óles)', 'Ã“— „«—Ì«‰« «·‘„«·Ì…')
INSERT INTO PAYS VALUES ('MA', 'Maroc', '«·„€—»')
INSERT INTO PAYS VALUES ('MH', 'Marshall (Óles)', 'Ã“— „«—‘«·')
INSERT INTO PAYS VALUES ('MQ', 'Martinique', '„— ‰Ìﬂ')
INSERT INTO PAYS VALUES ('MU', 'Maurice (Óle)', '„Ê—Ì‘ÌÊ”')
INSERT INTO PAYS VALUES ('MR', 'Mauritanie', '„Ê—Ìÿ«‰Ì«')
INSERT INTO PAYS VALUES ('YT', 'Mayotte', '„«ÌÊÿÂ')
INSERT INTO PAYS VALUES ('MX', 'Mexique', '«·„ﬂ”Ìﬂ')
INSERT INTO PAYS VALUES ('MD', 'Moldavie', '„Ê·œ«›Ì«')
INSERT INTO PAYS VALUES ('MC', 'Monaco', '„Ê‰«ﬂÊ')
INSERT INTO PAYS VALUES ('MN', 'Mongolie', '„‰€Ê·Ì«')
INSERT INTO PAYS VALUES ('MS', 'Montserrat', '„Ê‰ ”—« ')
INSERT INTO PAYS VALUES ('MZ', 'Mozambique', '„Ê“„»Ìﬁ')
INSERT INTO PAYS VALUES ('MM', 'Myanmar', '„Ì«‰„«—')
INSERT INTO PAYS VALUES ('NA', 'Namibie', '‰«„Ì»Ì«')
INSERT INTO PAYS VALUES ('NR', 'Nauru', '‰«Ê—Ê')
INSERT INTO PAYS VALUES ('NI', 'Nicaragua', '‰Ìﬂ«—«€Ê «')
INSERT INTO PAYS VALUES ('NE', 'Niger', '«·‰ÌÃ—')
INSERT INTO PAYS VALUES ('NG', 'Nigeria', '‰ÌÃÌ—Ì«')
INSERT INTO PAYS VALUES ('NU', 'Niue', '‰ÌÊÌÂ')
INSERT INTO PAYS VALUES ('NF', 'Norfolk (Óle)', 'Ã“Ì—… ‰Ê—›Ê·ﬂ')
INSERT INTO PAYS VALUES ('NO', 'NorvËge', '«·‰—ÊÌÃ')
INSERT INTO PAYS VALUES ('NC', 'Nouvelle CalÈdonie', 'ﬂ«·ÌœÊ‰Ì« «·ÃœÌœ…')
INSERT INTO PAYS VALUES ('NZ', 'Nouvelle ZÈlande', '‰ÌÊ“Ì·‰œ«')
INSERT INTO PAYS VALUES ('NP', 'NÈpal', '«·‰Ì»«·')
INSERT INTO PAYS VALUES ('IO', 'OcÈan indien (Territoire britannique)', '«·„ÕÌÿ «·Â‰œÌ')
INSERT INTO PAYS VALUES ('OM', 'Oman', '⁄„«‰')
INSERT INTO PAYS VALUES ('UG', 'Ouganda', '—Ê«‰œ«')
INSERT INTO PAYS VALUES ('UZ', 'OuzbÈkistan', '√Ê“»ﬂ” «‰')
INSERT INTO PAYS VALUES ('PK', 'Pakistan', '»ﬂ” «‰')
INSERT INTO PAYS VALUES ('PW', 'Palau, Carolines (Óles)', '»«·«Ê')
INSERT INTO PAYS VALUES ('PS', 'Palestine', '›·”ÿÌ‰')
INSERT INTO PAYS VALUES ('PG', 'Papouasie-Nouvelle GuinÈe', '»«»Ê« €Ì‰Ì« «·ÃœÌœ…')
INSERT INTO PAYS VALUES ('PY', 'Paraguay', '«·»«—«€Ê«Ì')
INSERT INTO PAYS VALUES ('NL', 'Pays-Bas', 'ÂÊ·‰œ«')
INSERT INTO PAYS VALUES ('PH', 'Philippines', '«·›·»Ì‰')
INSERT INTO PAYS VALUES ('PN', 'Pitcairn (Óle)', 'Ã“— »Ì ﬂÌ—‰')
INSERT INTO PAYS VALUES ('PL', 'Pologne', '»Ê·Ê‰Ì«')
INSERT INTO PAYS VALUES ('PF', 'PolynÈsie franÁaise', '»Ê·Ì‰”Ì« «·›—‰”Ì…')
INSERT INTO PAYS VALUES ('PR', 'Porto-Rico', '»Ê— Ê —ÌﬂÊ')
INSERT INTO PAYS VALUES ('PT', 'Portugal', '«·»— €«·')
INSERT INTO PAYS VALUES ('PE', 'PÈrou', '«·»Ì—Ê')
INSERT INTO PAYS VALUES ('QA', 'Qatar', 'ﬁÿ—')
INSERT INTO PAYS VALUES ('RO', 'Roumanie', '—Ê„‰Ì«')
INSERT INTO PAYS VALUES ('RU', 'Russie (FÈdÈration)', '—Ê”Ì«')
INSERT INTO PAYS VALUES ('RW', 'Rwanda', '—Ê«‰œ«')
INSERT INTO PAYS VALUES ('RE', 'RÈunion (Óle)', 'RÈunion (Óle)')
INSERT INTO PAYS VALUES ('EH', 'Sahara occidental', '«·’Õ—«¡ «·€—»Ì…')
INSERT INTO PAYS VALUES ('SH', 'Saint HÈlËne', '”«‰  Â·Ì‰«')
INSERT INTO PAYS VALUES ('KN', 'Saint Kitts and Nevis', '”«‰  ﬂÌ ” Ê‰Ì›Ì”')
INSERT INTO PAYS VALUES ('PM', 'Saint Pierre et Miquelon', '”«‰ »Ì«— Ê„Ìﬂ·Ê‰')
INSERT INTO PAYS VALUES ('VC', 'Saint Vincent et les Grenadines', '”«‰  ›‰”Ì‰  Ê«·Ã—Ì‰«œÌ‰“')
INSERT INTO PAYS VALUES ('SM', 'Saint-Marin', '”«‰ „«— Ì‰')
INSERT INTO PAYS VALUES ('LC', 'Sainte Lucie', '”«‰  ·Ê”Ì«')
INSERT INTO PAYS VALUES ('SB', 'Salomon (Óles)', 'Ã“— ”·Ì„«‰')
INSERT INTO PAYS VALUES ('WS', 'Samoa', '”«„Ê«')
INSERT INTO PAYS VALUES ('AS', 'Samoa orientales', '”«„Ê« «·‘—ﬁÌ…')
INSERT INTO PAYS VALUES ('ST', 'Sao Tome et Principe', '”«Ê  Ê„Ì Ê»—Ì‰”Ì»Ì')
INSERT INTO PAYS VALUES ('SC', 'Seychelles', '”Ì‘Ì·')
INSERT INTO PAYS VALUES ('SL', 'Sierra Leone', '”Ì—«·ÌÊ‰')
INSERT INTO PAYS VALUES ('SG', 'Singapour', '”‰€«›Ê—…')
INSERT INTO PAYS VALUES ('SK', 'Slovaquie', '”·Ê›«ﬂÌ«')
INSERT INTO PAYS VALUES ('SI', 'SlovÈnie', '”·Ê›Ì‰Ì«')
INSERT INTO PAYS VALUES ('SO', 'Somalie', '«·’Ê„«·')
INSERT INTO PAYS VALUES ('SD', 'Soudan', 'hgs')
INSERT INTO PAYS VALUES ('LK', 'Sri Lanka', '”—Ì·«‰ﬂ«')
INSERT INTO PAYS VALUES ('CH', 'Suisse', '”ÊÌ”—«')
INSERT INTO PAYS VALUES ('SR', 'Suriname', '”Ê—Ì‰«„')
INSERT INTO PAYS VALUES ('SE', 'SuËde', '«·”ÊÌœ')
INSERT INTO PAYS VALUES ('SZ', 'Swaziland', '”Ê«“Ì·‰œ')
INSERT INTO PAYS VALUES ('SY', 'Syrie', '”Ê—Ì«')
INSERT INTO PAYS VALUES ('SN', 'SÈnÈgal', '”‰€«·')
INSERT INTO PAYS VALUES ('TJ', 'Tadjikistan', 'ÿ«ÃÌﬂ” «‰')
INSERT INTO PAYS VALUES ('TW', 'Taiwan', ' «ÌÊ«‰')
INSERT INTO PAYS VALUES ('TZ', 'Tanzanie', ' ‰“«‰Ì«')
INSERT INTO PAYS VALUES ('CZ', 'TchËque (RÈpublique)', '«· ‘Ìﬂ')
INSERT INTO PAYS VALUES ('TH', 'ThaÔlande', ' «Ì·‰œ')
INSERT INTO PAYS VALUES ('TP', 'Timor oriental', ' Ì„Ê— «·‘—ﬁÌ…')
INSERT INTO PAYS VALUES ('TG', 'Togo', ' Ê€Ê')
INSERT INTO PAYS VALUES ('TK', 'Tokelau', ' Êﬂ·Ê')
INSERT INTO PAYS VALUES ('TO', 'Tonga', ' Ê‰€«')
INSERT INTO PAYS VALUES ('TT', 'TrinitÈ et Tobago', ' —Ì‰Ìœ«œ Ê Ê»«€Ê')
INSERT INTO PAYS VALUES ('TN', 'Tunisie', ' Ê‰”')
INSERT INTO PAYS VALUES ('TM', 'TurkmÈnistan', ' —ﬂ„‰” «‰')
INSERT INTO PAYS VALUES ('TC', 'Turks et CaÔques (Óles)', 'Ã“—  —ﬂ” Êﬂ«ÌﬂÊ”')
INSERT INTO PAYS VALUES ('TR', 'Turquie', ' —ﬂÌ«')
INSERT INTO PAYS VALUES ('TV', 'Tuvalu', ' Ê›«·Ê')
INSERT INTO PAYS VALUES ('UA', 'Ukraine', '√Êﬂ—«‰Ì«')
INSERT INTO PAYS VALUES ('UY', 'Uruguay', '«·√Ê—Ê€Ê«Ì')
INSERT INTO PAYS VALUES ('VU', 'Vanuatu', '›«‰Ê« Ê')
INSERT INTO PAYS VALUES ('VA', 'Vatican (Saint-SiËge)', '«·›« Ìﬂ«‰')
INSERT INTO PAYS VALUES ('VE', 'Venezuela', '›‰“ÊÌ·«')
INSERT INTO PAYS VALUES ('VI', 'Vierges (Óles amÈricaines)', '«·Ã“— «·⁄–—«¡ «·√„—ÌﬂÌ…')
INSERT INTO PAYS VALUES ('VG', 'Vierges (Óles britanniques)', '«·Ã“— «·⁄–—«¡ «·»—Ìÿ«‰Ì…')
INSERT INTO PAYS VALUES ('VN', 'ViÍt-nam', '›Ì ‰«„')
INSERT INTO PAYS VALUES ('WF', 'Wallis et Futuna', 'Ê«·” Ê›Ê Ê‰«')
INSERT INTO PAYS VALUES ('YU', 'Yougoslavie', 'ÌÊ€”·«›Ì«')
INSERT INTO PAYS VALUES ('YE', 'YÈmen', '«·Ì„‰')
INSERT INTO PAYS VALUES ('ZM', 'Zambie', '“„»Ì«')
INSERT INTO PAYS VALUES ('ZR', 'ZaÔre', '“ÌÌ—')
INSERT INTO PAYS VALUES ('ZW', 'Zimbabwe', '“„»«»ÊÌ')
PRINT '*** FONCTION ***'
INSERT INTO FONCTION VALUES ('005', 'Acteur', '„„À·', '', '')
INSERT INTO FONCTION VALUES ('010', 'Adapteur', '„ÕÊ—', '', 'Adapt.')
INSERT INTO FONCTION VALUES ('020', 'Annotateur', '„⁄·ﬁ ÕÊ«‘Ï', '', 'Comment.')
INSERT INTO FONCTION VALUES ('030', 'Arrangeur', '„Ê“⁄', '', 'Adapt.')
INSERT INTO FONCTION VALUES ('040', 'Artiste', '›‰«‰', '', '')
INSERT INTO FONCTION VALUES ('050', 'Titulaire des droits', '„«·ﬂ «·ÕﬁÊﬁ', '', '')
INSERT INTO FONCTION VALUES ('060', 'Nom associÈ', '«”„ „ﬁ —‰', '', '')
INSERT INTO FONCTION VALUES ('065', 'Commissaire-priseur', 'Commissaire-priseur', '', '')
INSERT INTO FONCTION VALUES ('070', 'Auteur', '„ƒ·›', '', '')
INSERT INTO FONCTION VALUES ('072', 'Auteur d''''une citation ou d''''extraits', '„ƒ·› «·≈” ‘Â«œ', '', '')
INSERT INTO FONCTION VALUES ('075', 'Postfacier, auteur du colophon, etc', '„ƒ·› „·Õﬁ', '', 'Postf.')
INSERT INTO FONCTION VALUES ('080', 'PrÈfacier, etc', '„ƒ·› „ﬁœ„…', '', 'PrÈf.')
INSERT INTO FONCTION VALUES ('090', 'Auteur du script, dialoguiste', '„ƒ·› —Ê«Ì…', '', '')
INSERT INTO FONCTION VALUES ('100', 'Auteur d''''oeuvres adaptÈes', '„ƒ·› „’‰› „ﬁ »”', '', '')
INSERT INTO FONCTION VALUES ('110', 'Relieur', '„Ã·œ', '', '')
INSERT INTO FONCTION VALUES ('120', 'Dessinateur de la reliure', '„’„„  Ã·Ìœ', '', 'ill.')
INSERT INTO FONCTION VALUES ('130', 'Maquettiste', '„’„„ ﬂ «»', '', '')
INSERT INTO FONCTION VALUES ('140', 'Dessinateur de la jaquette', '„’„„ €·«› «·Ã«—ÃÌ', '', 'ill.')
INSERT INTO FONCTION VALUES ('150', 'Dessinateur d''''ex-libris', '„’„„ ·ÊÕ«  «·ﬂ «»', '', 'ill.')
INSERT INTO FONCTION VALUES ('160', 'Libraire', '»«∆⁄ ﬂ »', '', '')
INSERT INTO FONCTION VALUES ('170', 'Calligraphe', 'Œÿ«ÿ', '', '')
INSERT INTO FONCTION VALUES ('180', 'Cartographe', '—«”„ Œ—«∆ÿ', '', '')
INSERT INTO FONCTION VALUES ('190', 'Censeur', '—ﬁÌ»', '', '')
INSERT INTO FONCTION VALUES ('200', 'ChorÈgraphe', '„’„„ —ﬁ’« ', '', '')
INSERT INTO FONCTION VALUES ('205', 'Collaborateur', '„”«⁄œ', '', 'Collab.')
INSERT INTO FONCTION VALUES ('210', 'Commentateur, confÈrencier', '„⁄·ﬁ', '', 'Comment.')
INSERT INTO FONCTION VALUES ('212', 'Commentateur de texte Ècrit', 'Commentateur de texte Ècrit', '', 'Comment.')
INSERT INTO FONCTION VALUES ('220', 'Compilateur', 'Ã«„⁄', '', 'Ed.')
INSERT INTO FONCTION VALUES ('230', 'Compositeur', '„·Õ‰', '', '')
INSERT INTO FONCTION VALUES ('240', 'Compositeur typographe', '„‰÷œ Õ—Ê›', '', '')
INSERT INTO FONCTION VALUES ('245', 'Concepteur', '„’„„', '', '')
INSERT INTO FONCTION VALUES ('250', 'Chef d''''orchestre', 'ﬁ«∆œ ›—ﬁ… „Ê”ﬁÌ…', '', '')
INSERT INTO FONCTION VALUES ('260', 'DÈtenteur de copyright', '’«Õ» ÕﬁÊﬁ «·ÿ»⁄', '', '')
INSERT INTO FONCTION VALUES ('270', 'Correcteur', '„’ÕÕ', '', '')
INSERT INTO FONCTION VALUES ('273', 'Commissaire d''''une exposition', '„› ‘ „⁄—÷', '', '')
INSERT INTO FONCTION VALUES ('274', 'Danseur', '—«ﬁ’', '', '')
INSERT INTO FONCTION VALUES ('280', 'DÈdicataire', '„ÂœÏ ≈·ÌÂ', '', '')
INSERT INTO FONCTION VALUES ('290', 'Auteur d''''une dÈdicace', '„ÂœÌ', '', '')
INSERT INTO FONCTION VALUES ('300', 'Directeur artistique', '„Œ—Ã', '', 'Dir.')
INSERT INTO FONCTION VALUES ('305', 'Doctorant', 'ÿ«·» œﬂ Ê—«Â', '', '')
INSERT INTO FONCTION VALUES ('310', 'Distributeur', '„Ê“⁄', '', '')
INSERT INTO FONCTION VALUES ('320', 'Donateur', '„«‰Õ', '', '')
INSERT INTO FONCTION VALUES ('330', 'Auteur douteux', '„ƒ·› „‘»ÊÂ', '', '')
INSERT INTO FONCTION VALUES ('340', 'Editeur (scientifique)', '(‰«‘— (⁄·„Ì', '', 'Ed.')
INSERT INTO FONCTION VALUES ('350', 'Graveur', '‰«ﬁ‘', '', 'ill.')
INSERT INTO FONCTION VALUES ('360', 'Aquafortiste', 'Aquafortiste', '', '')
INSERT INTO FONCTION VALUES ('365', 'Expert', 'Œ»Ì—', '', '')
INSERT INTO FONCTION VALUES ('370', 'RÈalisateur de film', '„Õ—— ›Ì·„', '', '')
INSERT INTO FONCTION VALUES ('380', 'Contrefacteur, faussaire', '„ﬁ·œ', '', '')
INSERT INTO FONCTION VALUES ('390', 'PropriÈtaire prÈcÈdent', '«·„«·ﬂ «·”«»ﬁ', '', '')
INSERT INTO FONCTION VALUES ('400', 'MÈcËne', '„„Ê· —«⁄Ì', '', '')
INSERT INTO FONCTION VALUES ('410', 'Technicien graphique', '›‰Ì Œÿ«ÿ', '', '')
INSERT INTO FONCTION VALUES ('420', 'Personne honorÈe', '’«Õ»  ﬂ—Ì„', '', '')
INSERT INTO FONCTION VALUES ('430', 'Enlumineur', '„“Œ—›', '', '')
INSERT INTO FONCTION VALUES ('440', 'Illustrateur', '—”«„', '', '')
INSERT INTO FONCTION VALUES ('450', 'Signataire d''''une prÈsentation', 'ﬂ« » «Âœ«¡', '', '')
INSERT INTO FONCTION VALUES ('460', 'Personne interviewÈe', '„ﬁ«»·', '', '')
INSERT INTO FONCTION VALUES ('470', 'Intervieweur', '„” ÃÊ»', '', '')
INSERT INTO FONCTION VALUES ('480', 'Librettiste', '„ƒ·› √Ê»—«', '', '')
INSERT INTO FONCTION VALUES ('490', 'Titulaire des droits (premier titulaire)', '(„«·ﬂ «·ÕﬁÊﬁ(„«·ﬂ «·√Ê·', '', '')
INSERT INTO FONCTION VALUES ('500', 'Concesseur', '„—Œ’', '', '')
INSERT INTO FONCTION VALUES ('510', 'Lithographe', 'ÿ«»⁄ «·ÕÃ—Ì', '', '')
INSERT INTO FONCTION VALUES ('520', 'Parolier', '„ƒ·› €‰«∆Ì', '', '')
INSERT INTO FONCTION VALUES ('530', 'Graveur sur mÈtal', '‰«ﬁ‘ „⁄œ‰', '', 'ill.')
INSERT INTO FONCTION VALUES ('540', 'ContrÙleur', '„—«ﬁ»/„ﬁ«»·', '', '')
INSERT INTO FONCTION VALUES ('545', 'Musicien, orchestre', '„Ê”Ìﬁ«—,›—ﬁ… „Ê”ÌﬁÌ…', '', '')
INSERT INTO FONCTION VALUES ('550', 'Narrateur', '—«ÊÌ', '', '')
INSERT INTO FONCTION VALUES ('560', 'CrÈateur', '„‰‘∆', '', '')
INSERT INTO FONCTION VALUES ('570', 'Autres', '√Œ—', '', '')
INSERT INTO FONCTION VALUES ('580', 'Fabricant de papier', '’«‰⁄ «·Ê—ﬁ', '', '')
INSERT INTO FONCTION VALUES ('590', 'InterprËte', '„ƒœÌ', '', '')
INSERT INTO FONCTION VALUES ('600', 'Photographe', '„’Ê—', '', 'ill.')
INSERT INTO FONCTION VALUES ('610', 'Imprimeur', 'ÿ«»⁄', '', '')
INSERT INTO FONCTION VALUES ('620', 'Imprimeur de gravures', 'ÿ«»⁄ ·ÊÕ« ', '', '')
INSERT INTO FONCTION VALUES ('630', 'Producteur', '„‰ Ã', '', '')
INSERT INTO FONCTION VALUES ('635', 'Programmeur', '„»—„Ã', '', '')
INSERT INTO FONCTION VALUES ('640', 'Correcteur d''''epreuves', '„’ÕÕ «·≈„ Õ«‰« ', '', '')
INSERT INTO FONCTION VALUES ('650', 'Editeur commercial', '‰«‘—  Ã«—Ì', '', 'Ed.')
INSERT INTO FONCTION VALUES ('651', 'Directeur de publication', '„œÌ— «·‰‘—', '', 'Dir.')
INSERT INTO FONCTION VALUES ('660', 'RÈcepteur d''''une correspondance', '„—”· «·ÌÂ', '', '')
INSERT INTO FONCTION VALUES ('670', 'IngÈnieur du son', '„Â‰œ” «·’Ê ', '', '')
INSERT INTO FONCTION VALUES ('675', 'Critique', '‰«ﬁœ', '', '')
INSERT INTO FONCTION VALUES ('690', 'ScÈnariste', 'ﬂ« » ”Ì‰«—ÌÊ', '', '')
INSERT INTO FONCTION VALUES ('695', 'Conseiller scientifique', '„” ‘«— ⁄·„Ì', '', '')
INSERT INTO FONCTION VALUES ('700', 'Scribe/copiste', '‰«”Œ', '', '')
INSERT INTO FONCTION VALUES ('705', 'Sculpteur', '‰Õ« ', '', '')
INSERT INTO FONCTION VALUES ('710', 'RÈdacteur en chef, rÈdacteur (AttachÈ de presse)', '—∆Ì”  Õ—Ì—', '', 'RÈd.')
INSERT INTO FONCTION VALUES ('720', 'Signataire', '„Êﬁ⁄', '', '')
INSERT INTO FONCTION VALUES ('721', 'Chanteur', '„€‰Ì', '', '')
INSERT INTO FONCTION VALUES ('723', 'Commanditaire', '„œ»—', '', '')
INSERT INTO FONCTION VALUES ('727', 'Directeur de thËse', '„œÌ— «·»ÕÀ', '', 'Dir.')
INSERT INTO FONCTION VALUES ('730', 'Traducteur', '„ —Ã„', '', 'Trad.')
INSERT INTO FONCTION VALUES ('740', 'Dessinateur de caractËres d''''imprimerie', '„’„„ ’› Õ—Ê›', '', 'ill.')
INSERT INTO FONCTION VALUES ('750', 'Typographe', 'ÿ»«⁄', '', '')
INSERT INTO FONCTION VALUES ('760', 'Graveur sur bois', '‰«ﬁ‘ Œ‘»', '', 'ill.')
INSERT INTO FONCTION VALUES ('770', 'Auteur du matÈriel d''''accompagnement', 'ﬂ« » „«œ… „—«›ﬁ…', '', '')
PRINT '*** CATEGORIE ***'
INSERT INTO CATEGORIE VALUES (1, 'Etudiant', 365, 10, 0)
INSERT INTO CATEGORIE VALUES (2, 'Enseignant', 365, 5, 0)
INSERT INTO CATEGORIE VALUES (3, 'EmployÈ', 365, 10, 0)
INSERT INTO CATEGORIE VALUES (9, 'Responsable de PEB', 365, 0, 0)
PRINT '*** MOT_VIDE ***'
INSERT INTO MOT_VIDE VALUES('le')
INSERT INTO MOT_VIDE VALUES('la')
INSERT INTO MOT_VIDE VALUES('les')
INSERT INTO MOT_VIDE VALUES('l')
INSERT INTO MOT_VIDE VALUES('du')
INSERT INTO MOT_VIDE VALUES('de')
INSERT INTO MOT_VIDE VALUES('des')
INSERT INTO MOT_VIDE VALUES('d')
INSERT INTO MOT_VIDE VALUES('a')
INSERT INTO MOT_VIDE VALUES('un')
INSERT INTO MOT_VIDE VALUES('une')
INSERT INTO MOT_VIDE VALUES('et')
INSERT INTO MOT_VIDE VALUES('t')
INSERT INTO MOT_VIDE VALUES('au')
INSERT INTO MOT_VIDE VALUES('aux')
INSERT INTO MOT_VIDE VALUES('en')
INSERT INTO MOT_VIDE VALUES('about')
INSERT INTO MOT_VIDE VALUES('an')
INSERT INTO MOT_VIDE VALUES('and')
INSERT INTO MOT_VIDE VALUES('are')
INSERT INTO MOT_VIDE VALUES('as')
INSERT INTO MOT_VIDE VALUES('at')
INSERT INTO MOT_VIDE VALUES('be')
INSERT INTO MOT_VIDE VALUES('by')
INSERT INTO MOT_VIDE VALUES('com')
INSERT INTO MOT_VIDE VALUES('for')
INSERT INTO MOT_VIDE VALUES('from')
INSERT INTO MOT_VIDE VALUES('how')
INSERT INTO MOT_VIDE VALUES('I')
INSERT INTO MOT_VIDE VALUES('if')
INSERT INTO MOT_VIDE VALUES('in')
INSERT INTO MOT_VIDE VALUES('is')
INSERT INTO MOT_VIDE VALUES('of')
INSERT INTO MOT_VIDE VALUES('on')
INSERT INTO MOT_VIDE VALUES('that')
INSERT INTO MOT_VIDE VALUES('the')
INSERT INTO MOT_VIDE VALUES('this')
INSERT INTO MOT_VIDE VALUES('to')
INSERT INTO MOT_VIDE VALUES('was')
INSERT INTO MOT_VIDE VALUES('what')
INSERT INTO MOT_VIDE VALUES('when')
INSERT INTO MOT_VIDE VALUES('where')
INSERT INTO MOT_VIDE VALUES('who')
INSERT INTO MOT_VIDE VALUES('with')
INSERT INTO MOT_VIDE VALUES('www')
PRINT '*** SPECIALITE ***'
INSERT INTO SPECIALITE VALUES ('1', 'Administration et Gestion Sportive', '≈œ«—… Ê ”ÌÌ— —Ì«÷Ì')
INSERT INTO SPECIALITE VALUES ('2', 'AÈronautique', '⁄·„ «·ÿÌ—«‰')
INSERT INTO SPECIALITE VALUES ('3', 'Agronomie', '›·«Õ…')
INSERT INTO SPECIALITE VALUES ('4', 'AmÈnagement', ' ÂÌ∆…')
INSERT INTO SPECIALITE VALUES ('5', 'Anthropologie', '√‰ —»Ê·ÊÃÌ«')
INSERT INTO SPECIALITE VALUES ('6', 'ArchÈologie', '⁄·„ «·¬À«—')
INSERT INTO SPECIALITE VALUES ('7', 'Architecture', 'Â‰œ”… „⁄„«—Ì…')
INSERT INTO SPECIALITE VALUES ('8', 'Arts du Spectacle', '›‰Ê‰ «·⁄—÷ «·„”—ÕÌ')
INSERT INTO SPECIALITE VALUES ('9', 'Arts Plastiques', '›‰Ê‰ »·«” ÌﬂÌ…')
INSERT INTO SPECIALITE VALUES ('10', 'Assurances et Banques', ' √„Ì‰«  Ê »‰Êﬂ')
INSERT INTO SPECIALITE VALUES ('11', 'Automatique', '¬·Ì…')
INSERT INTO SPECIALITE VALUES ('12', 'BibliothÈconomie', '⁄·„ «·„ﬂ »« ')
INSERT INTO SPECIALITE VALUES ('13', 'Biologie', '»ÌÊ·ÊÃÌ«')
INSERT INTO SPECIALITE VALUES ('14', 'Biologie et Physiologie des Organismes', '»ÌÊ·ÊÃÌ« Ê ›Ì“ÌÊ·ÊÃÌ« ⁄÷ÊÌ…')
INSERT INTO SPECIALITE VALUES ('15', 'Biologie MolÈculaire et Cellulaire', '»ÌÊ·ÊÃÌ« Œ·ÊÌ… Ê –—Ì…')
INSERT INTO SPECIALITE VALUES ('16', 'Chimie', 'ﬂÌ„Ì«¡')
INSERT INTO SPECIALITE VALUES ('17', 'Chimie Industrielle', 'ﬂÌ„Ì«¡ ’‰«⁄Ì…')
INSERT INTO SPECIALITE VALUES ('18', 'Chirurgie Dentaire', 'Ã—«Õ… «·√”‰«‰')
INSERT INTO SPECIALITE VALUES ('19', 'Commerce International', ' Ã«—… œÊ·Ì…')
INSERT INTO SPECIALITE VALUES ('20', 'ComptabilitÈ ñ FiscalitÈ', '„Õ«”»… Ê ÷—«∆»')
INSERT INTO SPECIALITE VALUES ('21', 'Critique LittÈraire et ThÈ‚trale', '‰ﬁœ √œ»Ì Ê „”—ÕÌ')
INSERT INTO SPECIALITE VALUES ('22', 'DÈmographie', 'œÌ„€—«›Ì«')
INSERT INTO SPECIALITE VALUES ('23', 'Ecologie et Environnement', '≈ÌﬂÊ·ÊÃÌ« Ê »Ì∆…')
INSERT INTO SPECIALITE VALUES ('24', 'Education Physique et Sportive', '⁄·Ê„ Ê  ﬁ‰Ì«  «·‰‘«ÿ«  «·»œ‰Ì… «·—Ì«÷Ì…')
INSERT INTO SPECIALITE VALUES ('25', 'ElectromÈcanique', '≈·Ìﬂ —Ê„Ìﬂ«‰Ìﬂ')
INSERT INTO SPECIALITE VALUES ('26', 'Electronique', '≈·ﬂ —Ê‰Ìﬂ')
INSERT INTO SPECIALITE VALUES ('27', 'Electrotechnique', '«·ﬂ —Ê ﬁ‰Ì')
INSERT INTO SPECIALITE VALUES ('28', 'EnergÈtique', 'ÿ«ﬁÊÌ…')
INSERT INTO SPECIALITE VALUES ('29', 'EntraÓnement Sportif', ' œ—Ì» —Ì«÷Ì')
INSERT INTO SPECIALITE VALUES ('30', 'GÈnie Civil', 'Â‰œ”… „œ‰Ì…')
INSERT INTO SPECIALITE VALUES ('31', 'GÈnie Climatique', ' ﬂÌ› Ê  »—Ìœ')
INSERT INTO SPECIALITE VALUES ('32', 'GÈnie de l''Environnement', 'Â‰œ”… «·»Ì∆…')
INSERT INTO SPECIALITE VALUES ('33', 'GÈnie de la Maintenance', 'Â‰œ”… «·’Ì«‰…')
INSERT INTO SPECIALITE VALUES ('34', 'GÈnie des MatÈriaux', 'Â‰œ”… «·„Ê«œ')
INSERT INTO SPECIALITE VALUES ('35', 'GÈnie des ProcÈdÈs', 'Â‰œ”… «·ÿ—«∆ﬁ')
INSERT INTO SPECIALITE VALUES ('36', 'GÈnie des ProcÈdÈs Industriels', 'Â‰œ”… «·ÿ—«∆ﬁ «·’‰«⁄Ì…')
INSERT INTO SPECIALITE VALUES ('37', 'GÈnie Electrique et Electronique', 'Â‰œ”… ﬂÂ—»«∆Ì… Ê ≈·ﬂ —Ê‰Ìﬂ')
INSERT INTO SPECIALITE VALUES ('38', 'GÈnie Industriel', 'Â‰œ”… ’‰«⁄Ì…')
INSERT INTO SPECIALITE VALUES ('39', 'GÈnie Maritime', 'Â‰œ”… »Õ—Ì…')
INSERT INTO SPECIALITE VALUES ('40', 'GÈnie MÈcanique', 'Â‰œ”… „Ìﬂ«‰ÌﬂÌ…')
INSERT INTO SPECIALITE VALUES ('41', 'GÈnie Minier', 'Â‰œ”… „‰Ã„Ì…')
INSERT INTO SPECIALITE VALUES ('42', 'GÈnie rural', 'Â‰œ”… —Ì›Ì…')
INSERT INTO SPECIALITE VALUES ('43', 'GÈographie et AmÈnagement du Territoire', 'Ã€—«›Ì« Ê ÂÌ∆… «·≈ﬁ·Ì„')
INSERT INTO SPECIALITE VALUES ('44', 'GÈologie', 'ÃÌÊ·ÊÃÌ«')
INSERT INTO SPECIALITE VALUES ('45', 'GÈophysique', 'ÃÌÊ›“Ì«¡')
INSERT INTO SPECIALITE VALUES ('46', 'Gestion des Techniques Urbaines', ' ”ÌÌ— «· ﬁ‰Ì«  «·Õ÷—Ì…')
INSERT INTO SPECIALITE VALUES ('47', 'Histoire', ' «—ÌŒ')
INSERT INTO SPECIALITE VALUES ('48', 'Hydraulique', '—Ì')
INSERT INTO SPECIALITE VALUES ('49', 'Hydrocarbures et Chimie', '„Õ—Êﬁ«  Ê ﬂÌ„Ì«¡')
INSERT INTO SPECIALITE VALUES ('50', 'HydrogÈologie', 'ÂÌœ—ÊÃÌÊ·ÊÃÌ«')
INSERT INTO SPECIALITE VALUES ('51', 'HygiËne et SÈcuritÈ', '‰Ÿ«›… Ê √„‰')
INSERT INTO SPECIALITE VALUES ('52', 'HygiËne et SÈcuritÈ Industrielle', '‰Ÿ«›… Ê √„‰ ’‰«⁄Ì')
INSERT INTO SPECIALITE VALUES ('53', 'Industrie Alimentaire', '’‰«⁄… €–«∆Ì…')
INSERT INTO SPECIALITE VALUES ('54', 'Informatique', '≈⁄·«„ ¬·Ì')
INSERT INTO SPECIALITE VALUES ('55', 'Informatique de Gestion', '≈⁄·«„ ¬·Ì ·· ”ÌÌ—')
INSERT INTO SPECIALITE VALUES ('56', 'IngÈnieur en nutrition et Technologie Agroalimentaire', '„Â‰œ” ›Ì «· €–Ì… Ê «· ﬂ‰Ê·ÊÃÌ« «·“—«⁄Ì… «·€–«∆Ì…')
INSERT INTO SPECIALITE VALUES ('57', 'Langue Allemande', '¬œ«» Ê·€… √·„«‰Ì…')
INSERT INTO SPECIALITE VALUES ('58', 'Langue Anglaise', '¬œ«» Ê·€… ≈‰Ã·Ì“Ì…')
INSERT INTO SPECIALITE VALUES ('59', 'Langue Espagnole', '¬œ«» Ê·€… ≈”»«‰Ì…')
INSERT INTO SPECIALITE VALUES ('60', 'Langue et culture Amazighes', '·€… ÊÀﬁ«›… √„«“Ì€Ì…')
INSERT INTO SPECIALITE VALUES ('61', 'Langue et LittÈrature Arabe', '·€… Ê √œ» ⁄—»Ì')
INSERT INTO SPECIALITE VALUES ('62', 'Langue FranÁaise', '¬œ«» Ê·€… ›—‰”Ì…')
INSERT INTO SPECIALITE VALUES ('63', 'Langue Italienne', '¬œ«» Ê·€… ≈Ìÿ«·Ì…')
INSERT INTO SPECIALITE VALUES ('64', 'Langue Russe', '¬œ«» Ê·€… —Ê”Ì…')
INSERT INTO SPECIALITE VALUES ('65', 'Maintenance et SÈcuritÈ Industrielle', '’Ì«‰… Ê √„‰ ’‰«⁄Ì')
INSERT INTO SPECIALITE VALUES ('66', 'MathÈmatiques', '—Ì«÷Ì« ')
INSERT INTO SPECIALITE VALUES ('67', 'MÈdecine', 'ÿ»')
INSERT INTO SPECIALITE VALUES ('68', 'MÈtallurgie', ' ⁄œÌ‰')
INSERT INTO SPECIALITE VALUES ('69', 'Mines', '„‰«Ã„')
INSERT INTO SPECIALITE VALUES ('70', 'Optique et MÈcanique de PrÈcision', '»’—Ì«  Ê „Ìﬂ«‰Ìﬂ «·÷»ÿ')
INSERT INTO SPECIALITE VALUES ('71', 'Orthophonie', '√—ÿ›Ê‰Ì«')
INSERT INTO SPECIALITE VALUES ('72', 'Pharmacie', '’Ìœ·…')
INSERT INTO SPECIALITE VALUES ('73', 'Philosophie', '›·”›…')
INSERT INTO SPECIALITE VALUES ('74', 'Physique', '›Ì“Ì«¡')
INSERT INTO SPECIALITE VALUES ('75', 'Planification et Statistique', ' ŒÿÌÿ Ê ≈Õ’«¡')
INSERT INTO SPECIALITE VALUES ('76', 'Psychologie', '⁄·„ «·‰›”')
INSERT INTO SPECIALITE VALUES ('77', 'Psychologie, Sciences de l''Education et Orthophonie', '⁄·„ ‰›” Ê ⁄·Ê„ «· —»Ì… Ê √—ÿ›Ê‰Ì«')
INSERT INTO SPECIALITE VALUES ('78', 'Sciences Commerciales', '⁄·Ê„  Ã«—Ì…')
INSERT INTO SPECIALITE VALUES ('79', 'Sciences Commerciales et FinanciËres', '⁄·Ê„  Ã«—Ì… Ê „«·Ì…')
INSERT INTO SPECIALITE VALUES ('80', 'Sciences de Gestion', '⁄·Ê„ «· ”ÌÌ—')
INSERT INTO SPECIALITE VALUES ('81', 'Sciences de l''Education', '⁄·Ê„ «· —»Ì…')
INSERT INTO SPECIALITE VALUES ('82', 'Sciences de l''Information et Communication', '⁄·Ê„ «·≈⁄·«„ Ê «·« ’«·')
INSERT INTO SPECIALITE VALUES ('83', 'Sciences de la Mer', '⁄·Ê„ «·»Õ—')
INSERT INTO SPECIALITE VALUES ('84', 'Sciences de la Terre (gÈographie ñ cartographie)', '⁄·Ê„ «·√—÷ ( Ã€—«›Ì« Ê⁄·„ «·Œ—«∆ÿ )')
INSERT INTO SPECIALITE VALUES ('85', 'Sciences de la Terre (GÈologie)', '⁄·Ê„ «·√—÷ ( ÃÌÊ·ÊÃÌ« )')
INSERT INTO SPECIALITE VALUES ('86', 'Sciences Economiques', '⁄·Ê„ «ﬁ ’«œÌ…')
INSERT INTO SPECIALITE VALUES ('87', 'Sciences et Techniques des ActivitÈs Physiques et Sportives', '⁄·Ê„ Ê  ﬁ‰Ì«  «·‰‘«ÿ«  «·»œ‰Ì… «·—Ì«÷Ì…')
INSERT INTO SPECIALITE VALUES ('88', 'Sciences FinanciËres', '⁄·Ê„ „«·Ì…')
INSERT INTO SPECIALITE VALUES ('89', 'Sciences Islamiques', '⁄·Ê„ ≈”·«„Ì…')
INSERT INTO SPECIALITE VALUES ('90', 'Sciences Juridiques', 'ÕﬁÊﬁ')
INSERT INTO SPECIALITE VALUES ('91', 'Sciences Politiques', '⁄·Ê„ ”Ì«”Ì…')
INSERT INTO SPECIALITE VALUES ('92', 'Sciences Politiques et Relations Internationales', '⁄·Ê„ ”Ì«”Ì… Ê ⁄·«ﬁ«  œÊ·Ì…')
INSERT INTO SPECIALITE VALUES ('93', 'Sciences VÈtÈrinaires', '⁄·Ê„ «·»Ìÿ—…')
INSERT INTO SPECIALITE VALUES ('94', 'Sociologie', '⁄·„ «·«Ã „«⁄')
INSERT INTO SPECIALITE VALUES ('95', 'Sociologie et DÈmographie', '⁄·„ «Ã „«⁄ Ê œÌ„€—«›Ì«')
INSERT INTO SPECIALITE VALUES ('96', 'Sport', '—Ì«÷…')
INSERT INTO SPECIALITE VALUES ('97', 'Traduction ñ InterprÈtariat', ' —Ã„…')
INSERT INTO SPECIALITE VALUES ('98', 'Traitement des Eaux et Fluides Industriels', '„⁄«·Ã… «·„Ì«Â Ê «·≈›—«“«  «·’‰«⁄Ì…')
INSERT INTO SPECIALITE VALUES ('99', 'Travaux Publics', '√‘€«· ⁄„Ê„Ì…')
PRINT '*** DIPLOME ***'
INSERT INTO DIPLOME VALUES ('1', 'Licence-LMD', '·Ì”«‰”- · „ œ')
INSERT INTO DIPLOME VALUES ('2', 'Master-LMD', '„«” —- · „ œ')
INSERT INTO DIPLOME VALUES ('3', 'Doctorat-LMD', '- · „ œ œﬂ Ê—«Â')
INSERT INTO DIPLOME VALUES ('4', 'DiplÙme d''Ètudes universitaires appliquÈes DUEA', '‘Â«œ… «·œ—«”«  «·Ã«„⁄Ì… «· ÿ»ÌﬁÌ…')
INSERT INTO DIPLOME VALUES ('5', 'Licence', '·Ì”«‰”')
INSERT INTO DIPLOME VALUES ('6', 'DiplÙme d''Ètudes supÈrieures DES', '‘Â«œ… «·œ—«”«  «·⁄·Ì«')
INSERT INTO DIPLOME VALUES ('7', 'DiplÙme de professeur de l''enseignement fondamental PEF', '‘Â«œ… √” «– «· ⁄·Ì„ «·√”«”Ì')
INSERT INTO DIPLOME VALUES ('8', 'DiplÙme de professeur de l''enseignement secondaire PES', '‘Â«œ… √” «– «· ⁄·Ì„ «·À«‰ÊÌ')
INSERT INTO DIPLOME VALUES ('9', 'DiplÙme de professeur de l''enseignement secondaire technique PEST', '‘Â«œ… √” «– «· ⁄·Ì„ «·À«‰ÊÌ «· ﬁ‰Ì')
INSERT INTO DIPLOME VALUES ('10', 'DiplÙme d''ingÈnieur', '‘Â«œ… „Â‰œ”')
INSERT INTO DIPLOME VALUES ('11', 'DiplÙme d''architecte', '‘Â«œ… „Â‰œ” „⁄„«—Ì')
INSERT INTO DIPLOME VALUES ('12', 'DiplÙme de pharmacien', '‘Â«œ… ’Ìœ·«‰Ì')
INSERT INTO DIPLOME VALUES ('13', 'DiplÙme de chirurgien dentaire', '‘Â«œ… Ã—«Õ «·√”‰«‰')
INSERT INTO DIPLOME VALUES ('14', 'DiplÙme de docteur vÈtÈrinaire', '‘Â«œ… ÿ»Ì» »Ìÿ—Ì')
INSERT INTO DIPLOME VALUES ('15', 'DiplÙme de docteur en mÈdecine', '‘Â«œ… ÿ»Ì»')
INSERT INTO DIPLOME VALUES ('16', 'Magister', '„«Ã” Ì—')
INSERT INTO DIPLOME VALUES ('17', 'Doctorat', 'œﬂ Ê—«Â')
INSERT INTO PARAMETRE VALUES('DZ', 'BibliothËque', 3, NULL, NULL, NULL, NULL, NULL, NULL)
GO
